- name: "Install nginx"
  become: yes
  yum:
    name: nginx
  notify: Restart nginx

- name: "Modified Nginx configuration (Port change to 8080)"
  become: yes
  template:
    src: nginx_default.conf
    dest: /etc/nginx/conf.d/default.conf
  register: nginx_config_update_result

- name: "Start Nginx"
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  when: nginx_config_update_result.changed
