---
- hosts: webservers1
  vars_files:
    - configs/prod_config.yml
  tasks:
    - debug:
        msg: "{{nginx_config_update_result}}"
  roles:
    - nginx
    - nodejs

- hosts: webservers2
  vars_files:
    - configs/dev_config.yml
  roles:
    - nodejs
