- name: Add yum repository for nodejs
  become: yes
  yum_repository:
    name: nodejs
    description: nodejs
    baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
    gpgcheck: no
    enabled: yes

- name: "Install nodejs"
  become: yes
  yum:
    name: "nodejs-7.2.0"
